import { Role } from '@prisma/client';

export const PERMISSIONS = {
  BRANCH_READ: 'branch.read',
  BRANCH_WRITE: 'branch.write',
  CATALOG_READ: 'catalog.read',
  CATALOG_WRITE: 'catalog.write',
  RECIPE_READ: 'recipe.read',
  RECIPE_WRITE: 'recipe.write',
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_UPDATE: 'customer.update',
  PROMOTION_ACTIVE_READ: 'promotion.active.read',
  PROMOTION_READ: 'promotion.read',
  PROMOTION_WRITE: 'promotion.write',
  ANNOUNCEMENT_READ: 'announcement.read',
  ANNOUNCEMENT_WRITE: 'announcement.write',
  ATTENDANCE_SELF: 'attendance.self',
  ATTENDANCE_READ: 'attendance.read',
  SALARY_SELF: 'salary.self',
  SALARY_READ: 'salary.read',
  SALARY_WRITE: 'salary.write',
  SCHEDULE_SELF: 'schedule.self',
  SCHEDULE_READ: 'schedule.read',
  SCHEDULE_WRITE: 'schedule.write',
  USER_READ: 'user.read',
  USER_WRITE: 'user.write',
  USER_DELETE: 'user.delete',
  POS_ORDER_CREATE: 'pos.order.create',
  POS_ORDER_CHECKOUT: 'pos.order.checkout',
  POS_ORDER_READ: 'pos.order.read',
  POS_ORDER_CANCEL: 'pos.order.cancel',
  POS_ORDER_COMPENSATE: 'pos.order.compensate',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_RECEIVE: 'inventory.receive',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  FINANCE_CASH_FLOW_CREATE: 'finance.cash-flow.create',
  FINANCE_CASH_FLOW_READ: 'finance.cash-flow.read',
  FINANCE_SUMMARY_READ: 'finance.summary.read',
  REPORT_SALES_READ: 'report.sales.read',
  REPORT_INVENTORY_READ: 'report.inventory.read',
  PLATFORM_OPERATIONS_READ: 'platform.operations.read',
  PLATFORM_OUTBOX_REPLAY: 'platform.outbox.replay',
  PLATFORM_RETENTION_RUN: 'platform.retention.run',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ADMIN = [Role.SUPER_ADMIN] as const;
const ALL_AUTHENTICATED = [
  Role.SUPER_ADMIN,
  Role.MANAGER,
  Role.HR,
  Role.ACCOUNTANT,
  Role.CASHIER,
  Role.WAREHOUSE_STAFF,
  Role.KITCHEN_STAFF,
] as const;
const POS_OPERATORS = [Role.SUPER_ADMIN, Role.MANAGER, Role.CASHIER] as const;
const ORDER_READERS = [
  Role.SUPER_ADMIN,
  Role.MANAGER,
  Role.CASHIER,
  Role.ACCOUNTANT,
] as const;
const INVENTORY_OPERATORS = [
  Role.SUPER_ADMIN,
  Role.MANAGER,
  Role.WAREHOUSE_STAFF,
] as const;
const PEOPLE_MANAGERS = [Role.SUPER_ADMIN, Role.MANAGER, Role.HR] as const;
const FINANCE_OPERATORS = [
  Role.SUPER_ADMIN,
  Role.MANAGER,
  Role.ACCOUNTANT,
] as const;

export const PERMISSION_MATRIX = {
  [PERMISSIONS.BRANCH_READ]: ALL_AUTHENTICATED,
  [PERMISSIONS.BRANCH_WRITE]: ADMIN,
  [PERMISSIONS.CATALOG_READ]: ALL_AUTHENTICATED,
  [PERMISSIONS.CATALOG_WRITE]: ADMIN,
  [PERMISSIONS.RECIPE_READ]: INVENTORY_OPERATORS,
  [PERMISSIONS.RECIPE_WRITE]: ADMIN,
  [PERMISSIONS.CUSTOMER_READ]: POS_OPERATORS,
  [PERMISSIONS.CUSTOMER_CREATE]: POS_OPERATORS,
  [PERMISSIONS.CUSTOMER_UPDATE]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.PROMOTION_ACTIVE_READ]: POS_OPERATORS,
  [PERMISSIONS.PROMOTION_READ]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.PROMOTION_WRITE]: ADMIN,
  [PERMISSIONS.ANNOUNCEMENT_READ]: ALL_AUTHENTICATED,
  [PERMISSIONS.ANNOUNCEMENT_WRITE]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.ATTENDANCE_SELF]: ALL_AUTHENTICATED,
  [PERMISSIONS.ATTENDANCE_READ]: PEOPLE_MANAGERS,
  [PERMISSIONS.SALARY_SELF]: ALL_AUTHENTICATED,
  [PERMISSIONS.SALARY_READ]: [Role.SUPER_ADMIN, Role.ACCOUNTANT],
  [PERMISSIONS.SALARY_WRITE]: [Role.SUPER_ADMIN, Role.ACCOUNTANT],
  [PERMISSIONS.SCHEDULE_SELF]: ALL_AUTHENTICATED,
  [PERMISSIONS.SCHEDULE_READ]: PEOPLE_MANAGERS,
  [PERMISSIONS.SCHEDULE_WRITE]: PEOPLE_MANAGERS,
  [PERMISSIONS.USER_READ]: PEOPLE_MANAGERS,
  [PERMISSIONS.USER_WRITE]: PEOPLE_MANAGERS,
  [PERMISSIONS.USER_DELETE]: ADMIN,
  [PERMISSIONS.POS_ORDER_CREATE]: POS_OPERATORS,
  [PERMISSIONS.POS_ORDER_CHECKOUT]: POS_OPERATORS,
  [PERMISSIONS.POS_ORDER_READ]: ORDER_READERS,
  [PERMISSIONS.POS_ORDER_CANCEL]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.POS_ORDER_COMPENSATE]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.INVENTORY_READ]: INVENTORY_OPERATORS,
  [PERMISSIONS.INVENTORY_RECEIVE]: INVENTORY_OPERATORS,
  [PERMISSIONS.INVENTORY_ADJUST]: INVENTORY_OPERATORS,
  [PERMISSIONS.INVENTORY_TRANSFER]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.FINANCE_CASH_FLOW_CREATE]: FINANCE_OPERATORS,
  [PERMISSIONS.FINANCE_CASH_FLOW_READ]: FINANCE_OPERATORS,
  [PERMISSIONS.FINANCE_SUMMARY_READ]: [Role.SUPER_ADMIN, Role.ACCOUNTANT],
  [PERMISSIONS.REPORT_SALES_READ]: [Role.SUPER_ADMIN, Role.MANAGER],
  [PERMISSIONS.REPORT_INVENTORY_READ]: INVENTORY_OPERATORS,
  [PERMISSIONS.PLATFORM_OPERATIONS_READ]: ADMIN,
  [PERMISSIONS.PLATFORM_OUTBOX_REPLAY]: ADMIN,
  [PERMISSIONS.PLATFORM_RETENTION_RUN]: ADMIN,
} as const satisfies Record<Permission, readonly Role[]>;

export function roleHasPermission(role: Role, permission: Permission): boolean {
  return (PERMISSION_MATRIX[permission] as readonly Role[]).includes(role);
}

export function roleHasEveryPermission(
  role: Role,
  permissions: readonly Permission[],
): boolean {
  return permissions.every((permission) => roleHasPermission(role, permission));
}
